### ISSUE TITLE
Pipeline appears stalled for for some queues

### ISSUE THREAD

**Issue by julian1** [aodn/VIT#12]
Noticed @julian1 at 7.20am.

Nagios shows 20 critical
``` 
10-aws-syd.emii.org.au
	UP 	
87 OK
20 CRITICAL
	View Extended Information For This Host Perform Extra Host ActionsView Service Details For This Host Locate Host On Map
```

``` 	
input incoming FAIMMS
	
Perform Extra Service Actions
	CRITICAL 	2016-11-29 07:21:38 	7d 15h 21m 20s 	3/3 	CRITICAL: Directory '/mnt/ebs/incoming/FAIMMS' has '9676' files 
```

Confirmed on box,
```
root@10-aws-syd:~$ ls /mnt/ebs/incoming/FAIMMS | wc -l
9676

```

**Comment by julian1** [comment]
@pblain should be a VIT or taken into account in planning?

**Comment by bpasquer** [comment]
Not sure. Talend component iUpdateSaptialExtent is failing and  as far as i understand seems to be linked to an issue with Geonetwork

**Comment by julian1** [comment]
Perhaps network related - making the connection to GN. 

It's been included in planning as something to look at.

**Comment by jonescc** [comment]
FAIMMS issue resolved - liquibase lock removed.  
iUpdatespatialextent failing as catalogue-imos was down - its up now.
