### ISSUE TITLE
Latest ACORN files can't be viewed in the portal

### ISSUE THREAD

**Issue by jonescc** [aodn/VIT#19]
Hi All,

I’m just testing ACORn collections in systest and noticed there was an issue with ACORN real time collections and then checked prod and it is occurring there as well. The collections aren’t loading but they are still on the “good list” just showing the error triangle…

Can someone please take a look if not already investigating?

Cheers,
Kate

**Comment by jonescc** [comment]
Problem looks to be caused by a combination of the database index being updated prior to the file being available on s3 and caching of not found responses possibly exacerbated by the link_checker.

I've restarted thredds on the two eb instances which will have cleared the cache and the acorn layers should now be available until the next time this happens.

**Comment by julian1** [comment]
> would be to write an implementation of the Thredds virtual directory interface to drive object listings using the harvest index. 

https://github.com/aodn/internal-discussions/issues/301

**Comment by jonescc** [comment]
Reduced s3 recheck interval to 13 minutes in https://github.com/aodn/thredds/pull/12/files (to align with other default expiry times) and made it configurable in thredds config.   Will be systested next iteration and with any luck be promoted to production.   Until then will need to restart thredds if this happens again.
