### ISSUE TITLE
Harvesters missing from catalogue-imos

### ISSUE THREAD

**Issue by anguss00** [aodn/VIT#6]
Harvesters were created by @atkinsn according to the log files.

`2016-11-16 13:52:28,869 INFO  [jeeves.request] - HTML Request (from 131.217.38.79) : /geonetwork/srv/eng/xml.harvesting.add`

`2016-11-16 13:53:25,586 INFO  [jeeves.request] - HTML Request (from 131.217.38.79) : /geonetwork/srv/eng/xml.harvesting.add`

`2016-11-16 13:54:30,601 INFO  [jeeves.request] - HTML Request (from 131.217.38.79) : /geonetwork/srv/eng/xml.harvesting.add`

`2016-11-16 13:55:08,544 INFO  [jeeves.request] - HTML Request (from 131.217.38.79) : /geonetwork/srv/eng/xml.harvesting.add`

`2016-11-16 13:55:49,032 INFO  [jeeves.request] - HTML Request (from 131.217.38.79) : /geonetwork/srv/eng/xml.harvesting.add`

`2016-11-16 13:56:22,694 INFO  [jeeves.request] - HTML Request (from 131.217.38.79) : /geonetwork/srv/eng/xml.harvesting.add`

As of 2016-11-21 11.47 the harvesters were missing in catalogue-imos configuration.
Logs show no xml.harvester.delete ops from 2016-11-16 onwards.

**Comment by jonescc** [comment]
Harvesters found!
